repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.1
    hooks:
      # Run the linter.
      - id: ruff
        name: webserver-ruff
        pass_filenames: false
        args: [--config, WebServer/ruff.toml, --fix, WebServer/webapp]
      # Run the formatter.
      - id: ruff-format
        name: webserver-ruff-format
        pass_filenames: false
        args: [--config, WebServer/ruff.toml, WebServer/webapp]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        name: webserver-mypy
        pass_filenames: false
        additional_dependencies: [types-redis==4.6.0]
        args: [--config-file, WebServer/mypy.ini, WebServer/webapp, --ignore-missing-imports]
