apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: callminer-secrets-app
  namespace: default
spec:
  appName: ${APP_NAME}
  destination:
    create: true
    labels:
      hvs: "true"
    name: callminer-secrets
  refreshAfter: 1h