services:
  app:
    build:
      context: .
    restart: always
    network_mode: host
    volumes:
      - ./src:/app
      - ./public:/app/public
    env_file: ./.env
    depends_on:
      - redis
      - mongo
      - worker
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  redis:
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    scale: 1
    command: ['celery', '-A', 'tasks', 'worker', '-l', 'info']
    volumes:
      - ./src:/app
    env_file: ./.env
    depends_on:
      - redis
volumes:
  mongo_data:
