services:
  be:
    build:
      context: .
    restart: always
    network_mode: host
    volumes:
      - ./be:/app/be
    env_file: ./.env
    depends_on:
      - redis
      - mongo
      - celery_worker

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  redis:
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ 'celery', '-A', 'be.celery_app', 'worker', '-l', 'info' ]
    depends_on:
      - redis
      - mongo
    volumes:
      - ./be:/app/be
    env_file: ./.env
    restart: always
    scale: 3

volumes:
  mongo_data: