services:
  webapp:
    build:
      context: .
    restart: always
    network_mode: host
    volumes:
      - ./public:/app/public
      - ./webapp:/app/webapp
    env_file: ./.env
    depends_on:
      - redis
      - mongo
      - chromadb
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  redis:
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
  chromadb:
    image: chromadb/chroma:latest
    restart: always
    ports:
      - ${CHROMADB_PORT}:8000
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - CHROMA_SERVER_PORT=8000
volumes:
  mongo_data:
  chroma_data:
