services:
  ner:
    restart: always
    image: ner_model
    container_name: ner_model
    build:
      context: ./Models/NER
    ports:
      - "1234:1234"
    env_file:
      - .env
    environment:
      - MODEL=${NER_MODEL}

  gpt_summarizer:
    restart: always
    image: gpt_summarizer
    container_name: gpt_summarizer
    build:
      context: ./Models/gpt_summarizer
    ports:
      - "1235:1234"
    env_file:
      - .env
    environment:
      - MODEL=${GPT_SUMMARIZER_MODEL}
      - OPENAI_API_TYPE=${OPENAI_API_TYPE}
      - OPENAI_API_BASE=${AZURE_API_BASE}
      - OPENAI_API_KEY=${AZURE_API_KEY}
      - OPENAI_API_VERSION=${AZURE_API_VERSION}
      - OPENAI_DEPLOYMENT_NAME=${AZURE_GPT_4O_MINI_ENDPOINT}

  asr:
    restart: always
    image: asr_model
    container_name: asr_model
    shm_size: 2gb
    build:
      context: ./Models/ASR
    volumes:
      - ./Models/ASR/diar_infer_telephonic.yaml:/app/diar_infer_telephonic.yaml
    ports:
      - "1236:1234"
    env_file:
      - .env
    environment:
      - MODEL=${ASR_MODEL}
      - TIMEOUT=3000

  speaker_classifier:
    restart: always
    image: speaker_classifier
    container_name: speaker_classifier
    build:
      context: ./Models/speaker_classifier
    ports:
      - "1237:1234"
    env_file:
      - .env
    environment:
      - MODEL=${SPEAKER_CLASSIFIER_MODEL}
      - OPENAI_API_TYPE=${OPENAI_API_TYPE}
      - OPENAI_API_BASE=${AZURE_API_BASE}
      - OPENAI_API_KEY=${AZURE_API_KEY}
      - OPENAI_API_VERSION=${AZURE_API_VERSION}
      - OPENAI_DEPLOYMENT_NAME=${AZURE_GPT_4O_MINI_ENDPOINT}

  conformity_check:
    restart: always
    image: conformity_check
    container_name: conformity_check
    build:
      context: ./Models/conformity_check
    ports:
      - "1238:1234"
    env_file:
      - .env
    environment:
      - MODEL=${CONFORMITY_CHECK_MODEL}
      - OPENAI_API_TYPE=${OPENAI_API_TYPE}
      - OPENAI_API_BASE=${AZURE_API_BASE}
      - OPENAI_API_KEY=${AZURE_API_KEY}
      - OPENAI_API_VERSION=${AZURE_API_VERSION}
      - OPENAI_DEPLOYMENT_NAME=${AZURE_GPT_4O_MINI_ENDPOINT}