apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr
  template:
    metadata:
      labels:
        app: asr
    spec:
      containers:
        - name: asr
          image: callminerput/asr-model:v1.0
          ports:
            - containerPort: 1234
          env:
            - name: MODEL
              valueFrom:
                secretKeyRef:
                  name: callminer-secrets
                  key: ASR_MODEL
            - name: TIMEOUT
              value: "3000"
          envFrom:
            - secretRef:
                name: callminer-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: asr-service
spec:
  type: NodePort
  selector:
    app: asr
  ports:
    - protocol: TCP
      port: 1236
      targetPort: 1234
      nodePort: 31236